version: '3'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-monitoring
        container_name: laravel-monitoring
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
            - ./docker-config/php.ini:/etc/php8/conf.d/custom.ini
        networks:
            - mainapp
        depends_on:
            - database
        ports:
            - 8383:8080

    # npm:
    #     image: node:17-alpine
    #     container_name: laravel-npm
    #     restart: unless-stopped
    #     working_dir: /var/www/html
    #     entrypoint: ["npm"]
    #     depends_on:
    #     - app
    #     volumes:
    #     - ./:/var/www/html
            
networks:
    mainapp:
        name: mainapp
# volumes:
#     mysqldb:
#         driver: local