version: "3.9"

services:
  app:
    build:
      args:
        user: bali
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: monitoring_app
    container_name: monitoring_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring


